# Generated by Django 5.2.4 on 2025-07-30 14:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('cv_text', models.TextField(blank=True)),
                ('cv_parsed_data', models.JSONField(default=dict)),
                ('skills_extracted', models.JSONField(default=list)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('languages', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Reçu'), ('screening', 'Pré-sélection'), ('interview', 'Entretien'), ('tests', 'Test technique'), ('final', 'Entretien final'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('withdrawn', 'Retiré')], default='received', max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('ai_match_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_analysis', models.JSONField(default=dict)),
                ('cultural_fit_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', 'Téléphonique'), ('video', 'Visioconférence'), ('in_person', 'Présentiel'), ('ai_screening', 'Pré-sélection IA')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('questions', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='interviews/')),
                ('transcription', models.TextField(blank=True)),
                ('ai_evaluation', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.application')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('benefits', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('paused', 'En pause'), ('closed', 'Fermée')], default='draft', max_length=20)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior (0-2 ans)'), ('middle', 'Confirmé (2-5 ans)'), ('senior', 'Senior (5+ ans)')], max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(max_length=200)),
                ('remote_allowed', models.BooleanField(default=False)),
                ('contract_type', models.CharField(default='CDI', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('seo_optimized', models.BooleanField(default=False)),
                ('bias_checked', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.joboffer'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job_offer', 'candidate')},
        ),
    ]
