# Generated by Django 5.2.4 on 2025-08-18 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_locations', models.JSONField(default=list)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_contract_types', models.JSONField(default=list)),
                ('remote_preference', models.CharField(choices=[('required', 'Télétravail obligatoire'), ('preferred', 'Télétravail préféré'), ('accepted', 'Télétravail accepté'), ('refused', 'Présentiel uniquement')], default='accepted', max_length=20)),
                ('last_matching_update', models.DateTimeField(auto_now=True)),
                ('matching_active', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immédiat'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire')], default='weekly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_profile', to='recruitment.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='MatchingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField()),
                ('detailed_scores', models.JSONField(default=dict)),
                ('recommendation', models.CharField(max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidate')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.joboffer')),
            ],
            options={
                'indexes': [models.Index(fields=['overall_score'], name='recruitment_overall_0f01b5_idx'), models.Index(fields=['calculated_at'], name='recruitment_calcula_a3ac27_idx')],
                'unique_together': {('candidate', 'job_offer')},
            },
        ),
    ]
