# Generated by Django 5.2.4 on 2025-08-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_candidate_global_match_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Candidat', 'verbose_name_plural': 'Candidats'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='soft_skills',
            field=models.JSONField(default=list, help_text='Liste des compétences comportementales'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='technical_skills',
            field=models.JSONField(default=list, help_text='Liste des compétences techniques'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills_extracted',
            field=models.JSONField(blank=True, default=dict, help_text='Ancien format - sera déprécié'),
        ),
    ]
