# Generated by Django 5.2.5 on 2025-08-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_alter_candidate_options_candidate_soft_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='salary_min',
        ),
    ]
