# Generated by Django 5.2.5 on 2025-08-31 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_alter_application_candidate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du groupe')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_groupe', models.CharField(choices=[('competence', 'Par compétence'), ('experience', 'Par expérience'), ('projet', 'Par projet'), ('pipeline', 'Pipeline de recrutement'), ('performance', 'Par performance'), ('geographic', 'Par zone géographique'), ('custom', 'Personnalisé')], default='custom', max_length=20, verbose_name='Type de groupe')),
                ('couleur', models.CharField(choices=[('blue', 'Bleu'), ('green', 'Vert'), ('red', 'Rouge'), ('yellow', 'Jaune'), ('purple', 'Violet'), ('orange', 'Orange'), ('gray', 'Gris'), ('teal', 'Sarcelle')], default='blue', max_length=20, verbose_name='Couleur')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_public', models.BooleanField(default=False, verbose_name="Visible par tous les utilisateurs de l'entreprise")),
                ('auto_populate', models.BooleanField(default=False, verbose_name='Population automatique')),
                ('criteria_json', models.JSONField(blank=True, null=True, verbose_name='Critères automatiques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('candidats', models.ManyToManyField(blank=True, related_name='groupes', to='recruitment.candidate', verbose_name='Candidats')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Groupe de candidats',
                'verbose_name_plural': 'Groupes de candidats',
                'ordering': ['ordre_affichage', 'nom'],
                'constraints': [models.UniqueConstraint(fields=('nom', 'created_by'), name='unique_group_name_per_user')],
            },
        ),
    ]
