# Generated by Django 5.2.5 on 2025-09-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_groupcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv_file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='extraction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education_level',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('N/A', 'Non spécifié')], default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills_extracted',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='soft_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Nouveau'), ('pending_extraction', "En attente d'extraction"), ('reviewed', 'Examiné'), ('interviewed', 'Entretien'), ('hired', 'Embauché'), ('rejected', 'Rejeté')], default='pending_extraction', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='technical_skills',
            field=models.JSONField(default=list),
        ),
    ]
