# Generated by Django 5.2.5 on 2025-09-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_candidate_cv_file_path_candidate_extraction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv_embeddings',
            field=models.JSONField(blank=True, default=dict, help_text='Embeddings vectoriels organisés par section du CV en format JSON structuré', verbose_name='Embeddings structurés'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='embeddings_generated_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de génération des embeddings', null=True, verbose_name='Embeddings générés le'),
        ),
    ]
