# Generated by Django 5.2.5 on 2025-09-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_candidate_cv_embeddings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='matching_weights',
            field=models.JSONField(blank=True, default=dict, help_text="Poids personnalisés pour le matching (ex: {'technical_skills': 0.4, 'experience': 0.3, ...})"),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Prompt système spécifique pour ce job, utilisé par le modèle IA'),
        ),
    ]
